### PR TITLE
Support GHC 9.4

### PR DESCRIPTION
**Pull request by sjakobi**
~~Includes temporary `allow-newer` settings in `cabal.project`.~~

Blockers:

* [ ] https://github.com/haskellari/splitmix/issues/64

### CODE REVIEW

**Comment by sjakobi** [comment]
This warning should be addressed:

```
src/Data/YAML.hs:422:15: warning: [-Wtype-equality-requires-operators]
    The use of ‘~’ without TypeOperators
    will become an error in a future GHC release.
    Suggested fix: Perhaps you intended to use TypeOperators
    |
422 | instance (loc ~ Pos) => FromYAML (Node loc) where
    |               ^
```

**Comment by andreasabel** [comment]
You can add `tested-with: GHC == 9.4.1` which is supported by the development version of Haskell-CI (0.15.20220525).

**Comment by andreasabel** [comment]
> Suggested fix: Perhaps you intended to use TypeOperators

I'd say the best way is to simply add `TypeOperators` to the `default-extensions` in the cabal file.

**Review by andreasabel — APPROVED** [review]

**Comment by sjakobi** [comment]
Since I'm already getting a green build and test run with `--allow-newer`, I've bumped the `base` bound via a Hackage revision: https://hackage.haskell.org/package/HsYAML-0.2.1.1/revisions/

**Pull request merged**
